spring:
   datasource:
      url: jdbc:postgresql://localhost:5432/commandsdb
      username: postgres
      password: 123
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true
      show-sql: true